### ISSUE TITLE
Een h1 minder

### ISSUE THREAD

**Issue by Demivdm** [Nazneen05x/connect-your-tribe-profile-card#6]
Je kunt minder h1's gebruiken door een plusje te gebruiken zoals hier --> 
      <h1> member.name + "" + member.surname </h1>

https://github.com/Nazneen05x/connect-your-tribe-profile-card/blob/4992ddbc576849288b426d9edca111efe3dfc41d/views/index.ejs#L8

**Comment by Nazneen05x** [comment]
Nog bedankt voor je feedback! Echt een goeie tip! 

https://github.com/Nazneen05x/connect-your-tribe-profile-card/blob/main/views/index.ejs#L7-L9
