### ISSUE TITLE
Avatar uit data!

### ISSUE THREAD

**Issue by ju5tu5** [Nazneen05x/connect-your-tribe-profile-card#8]
https://github.com/Nazneen05x/connect-your-tribe-profile-card/blob/4992ddbc576849288b426d9edca111efe3dfc41d/views/index.ejs#L6

Je kunt je avatar uit de whois database halen.

**Comment by Nazneen05x** [comment]
Nog bedankt voor u feedback (issues)😃    

https://github.com/Nazneen05x/connect-your-tribe-profile-card/blob/main/views/index.ejs#L6
